### ISSUE TITLE
Add Focus area field and behaviors

### ISSUE THREAD

**Issue by kaerumy** [Sinar/foecluster.km#1]
Focus Areas
1.	Strengthening media 
2.	Film censorship
3.	Right to information
4.	Strengthening freedom of expression
5.	Internet censorship and digital rights

**Comment by chungisad** [comment]
The focus area is available in the search term settings in collection but it's not available in resource page, 
![image](https://user-images.githubusercontent.com/66195613/113261101-9e98da80-9301-11eb-9eb3-0c3555bd213c.png)
![image](https://user-images.githubusercontent.com/66195613/113261254-d1db6980-9301-11eb-922d-ee56ce50437f.png)
